# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='\u540d\u5b57')),
                ('sort', models.IntegerField(blank=True, verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='NavPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u63cf\u8ff0')),
                ('url', models.URLField(blank=True, verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('style', models.CharField(blank=True, choices=[('tile bg-red', '\u7ea2\u8272'), ('tile bg-green', '\u7eff\u8272'), ('tile bg-blue', '\u84dd\u8272'), ('tile bg-yellow', '\u6a58\u9ec4'), ('tile bg-grey', '\u7070\u8272')], max_length=100, verbose_name='\u989c\u8272')),
                ('ico', models.CharField(blank=True, default='fa fa-', max_length=100, verbose_name='\u56fe\u6807')),
                ('sort', models.IntegerField(blank=True, verbose_name='\u6392\u5e8f')),
                ('fenlei', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='navigation.Classify', verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u5bfc\u822a\u914d\u7f6e',
                'verbose_name_plural': '\u5bfc\u822a\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, default='\u4eca\u65e5\u65e0\u6d88\u606f', max_length=200, verbose_name='\u63cf\u8ff0')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u516c\u544a',
                'verbose_name_plural': '\u516c\u544a',
            },
        ),
    ]
