# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classify',
            options={'ordering': ['sort'], 'verbose_name': '\u5206\u7c7b', 'verbose_name_plural': '\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='navpage',
            options={'ordering': ['sort'], 'verbose_name': '\u5bfc\u822a\u914d\u7f6e', 'verbose_name_plural': '\u5bfc\u822a\u914d\u7f6e'},
        ),
    ]
