# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u540d')),
                ('ip', models.GenericIPAddressField(verbose_name='ip\u5730\u5740')),
                ('osversion', models.CharField(max_length=50, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('memory', models.CharField(max_length=50, verbose_name='\u5185\u5b58')),
                ('cpu_core', models.CharField(max_length=50, verbose_name='cpu\u6838\u6570')),
                ('disk', models.CharField(max_length=50, verbose_name='\u78c1\u76d8')),
            ],
        ),
    ]
