# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u7ec4\u540d')),
                ('members', models.ManyToManyField(to='hostinfo.Host', verbose_name='\u4e3b\u673a')),
            ],
        ),
    ]
